{% set name = "makefun" %}
{% set version = "1.16.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/makefun-{{ version }}.tar.gz
  sha256: e14601831570bff1f6d7e68828bcd30d2f5856f24bad5de0ccb22921ceebc947

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
    - setuptools_scm
  run:
    - python >={{ python_min }}

test:
  imports:
    - makefun
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/smarie/python-makefun
  summary: Small library to dynamically create python functions.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    `makefun` helps you create functions dynamically, with the signature of
    your choice. It was largely inspired by `decorator` and `functools`, and
    created mainly to cover some of their limitations.
  doc_url: https://smarie.github.io/python-makefun
  dev_url: https://github.com/smarie/python-makefun

extra:
  recipe-maintainers:
    - smarie
