{% set name = "makefun" %}
{% set version = "1.15.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/makefun-{{ version }}.tar.gz
  sha256: 16f2a2b34d9ee0c2b578c960a1808c974e2822cf79f6e9b9c455aace10882d45

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.5
    - setuptools_scm
  run:
    - python >=3.5

test:
  imports:
    - makefun
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/smarie/python-makefun
  summary: Small library to dynamically create python functions.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    `makefun` helps you create functions dynamically, with the signature of
    your choice. It was largely inspired by `decorator` and `functools`, and
    created mainly to cover some of their limitations.
  doc_url: https://smarie.github.io/python-makefun
  dev_url: https://github.com/smarie/python-makefun

extra:
  recipe-maintainers:
    - smarie
